export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOBS_FULFILLED = 'FETCH_JOBS_FULFILLED';
export const FETCH_JOBS_PENDING = 'FETCH_JOBS_PENDING';
export const FETCH_JOBS_REJECTED = 'FETCH_JOBS_REJECTED';